image: node:12

definitions:
  steps:
    - step: &Angular-Build
        name: Angular Build
        script:
          - npm install
          - npm run build
        caches:
          - node
        artifacts:
          - dist/**
    - step: &AWS-S3_Deploy_test
        name: S3-Test Deploy
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              S3_BUCKET: $AWS_S3_BUCKET_TEST
              LOCAL_PATH: "dist"
              ACL: "public-read"
              DELETE_FLAG: "true"
              EXTRA_ARGS: "--follow-symlinks"
    - step: &AWS-S3_Deploy_prod
        name: S3-Prod Deploy
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              S3_BUCKET: $AWS_S3_BUCKET_PROD
              LOCAL_PATH: "dist"
              ACL: "public-read"
              DELETE_FLAG: "true"
              EXTRA_ARGS: "--follow-symlinks"
pipelines:
  branches:
    master:
      - step: *Angular-Build
      - step: *AWS-S3_Deploy_prod
    next:
      - step: *Angular-Build
      - step: *AWS-S3_Deploy_test
  custom:
    deploy-to-prod:
      - step: *Angular-Build
      - step:
          <<: *AWS-S3_Deploy_prod
          name: S3-Prod Manual Deploy
    deploy-to-test:
      - step: *Angular-Build
      - step:
          <<: *AWS-S3_Deploy_test
          name: S3-Test Manual Deploy
